### ISSUE TITLE
Description of the code

### ISSUE THREAD

**Issue by sangsansang** [rcetin/booth_wallace_multiplier#1]
Is there a corresponding reference or documentation?
There are mainly the following doubts: 1. The  purpose of the shift signal and why it is directly equal to y. 2. Is the overall implementation of the 4booth and 3:2 wallace tree and the RCA?
Thanks

**Comment by rcetin** [comment]
Actually, i have implemented this long time ago. I think i have used this book as reference:
https://www.amazon.com/CMOS-VLSI-Design-Circuits-Perspective/dp/0321547748
